version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: dbt
    volumes:
      - postgres-db-volume:/var/lib/postgresql/dbt_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
volumes:
  postgres-db-volume: